name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run API Tests
        uses: postman/newman-action@v5
        with:
          collection: ${{ secrets.POSTMAN_COLLECTION_ID }}
          apiKey: ${{ secrets.POSTMAN_API_KEY }}
