name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Newman
        run: npm install -g newman
      
      - name: Run API Tests
        run: newman run "${{ secrets.POSTMAN_COLLECTION_ID }}"
        env:
          POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}
